### ISSUE TITLE
Plugin throws if (a python) file has syntax error

### ISSUE THREAD

**Issue by kaste** [kapitanluffy/sublime-semantic-highlighter#5]
With a syntax error in a Python file, for example

![image](https://user-images.githubusercontent.com/8558/98858651-4439d300-2461-11eb-8e56-5dba66e51d0d.png)

The plugin throws

```
Traceback (most recent call last):
  File "C:\Dev\Sublime Text 3\sublime_plugin.py", line 506, in run_async_view_listener_callback
    vel.__class__.__dict__[name](vel)
  File "C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Installed Packages\Semantic Highlighter.sublime-package\src/listeners/view_event.py", line 20, in on_selection_modified_async
    self.highlight()
  File "C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Installed Packages\Semantic Highlighter.sublime-package\src/listeners/view_event.py", line 36, in highlight
    highlighter.clear()
  File "C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Installed Packages\Semantic Highlighter.sublime-package\src/highlighter.py", line 58, in clear
    key = symbol.getKey()
  File "C:\Users\c-flo\AppData\Roaming\Sublime Text 3\Installed Packages\Semantic Highlighter.sublime-package\src/symbol.py", line 30, in getKey
    key = "%s.%s.%s.%s.%s" % ("plugin.semantic_highlighter", block.a, block.b, self.targetString, view)
AttributeError: 'bool' object has no attribute 'a'
```

**Comment by kapitanluffy** [comment]
Should be fixed in the latest 👍
